
name: CI
on: [push]

jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      
      - name: Check out code
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

        